### ISSUE TITLE
chore: agree on common naming convention for UEL experiments

### ISSUE THREAD

**Issue by mikkokotila** [Vaquum/Limen#64]
## Experiment Naming Convention - Standard Proposal

  Loop experiments use a content-addressed naming convention where names are deterministically generated from experiment YAML content. This ensures reproducibility, eliminates manual naming, and requires no central ID service.

  ### Naming Format

  {hash}{schema_version}[{suffix}]

  ### Components

  **hash** - SHA256 hash of canonical YAML content
  - Generated deterministically from experiment configuration
  - Same YAML always produces same hash
  - Serves as unique identifier for this experiment configuration
  
  **schema_version** - YAML format structure version
  - Defined in YAML `schema_version` field
  - Tracks evolution of YAML format itself (what fields are valid, structure changes)
  
  **suffix** - Optional run type identifier
  - Defines the type or purpose of the run
  - Examples: `prod`, `validation`
  - Note: Multiple runs of same experiment are tracked as separate Jobs

  ### Complete Example

  ```yaml
  # experiments/logreg_binary.yaml
  schema_version: v1
  suffix: prod
  parent_hash: a1b2c3d4  # Optional: links to parent experiment for lineage tracking

  manifest:
    data_source:
      method: HistoricalData.get_spot_klines
      params:
        kline_size: 3600
    indicators:
      - name: roc
        period: ${roc_period}
   ...
   ...
    model: logreg_binary

  params:
    roc_period: [1, 4, 12, 24]
    C: [0.1, 1.0, 10.0]
    ...

  uel_config:
    name: "Logreg-Binary-Quantile-Target"
    n_permutations: 1000

  metadata:
    description: "LogReg binary classifier with quantile targets"
    author: pdey
  ```
  Generated name: a3f5c2d8_v1_prod

  Where:
  - a3f5c2d8 = Hash of the manifest, params, and uel_config
  - v1 = YAML schema version
  - prod = Production run type

  Implementation

  - Experiments defined in YAML files stored in version control
  - Name generation extracts schema_version, manifest, params, and uel_config
  - Creates canonical representation excluding metadata, suffix, and parent_hash
  - Computes SHA256 hash and takes first 8-12 characters
  - Constructs final name by joining hash, schema_version, and optional suffix
  - Optional parent_hash field enables experiment lineage tracking in database
  - Both Experiments and Jobs are tracked in database with unique identifiers
